### ISSUE TITLE
Duplicate meta tags after binding `refreshLayout`

### ISSUE THREAD

**Issue by sasindu555** [janzheng/svelte-masonry#4]
I'm getting duplicated meta tags (meta description, meta keywords, ...) after binding `refreshLayout` on my svelteKit app. Without binding `refreshLayout` this duplication doesn't happen. SEO wise this is a serious issue for our site.

**Comment by janzheng** [comment]
I've removed all the meta tags stuff in the new Sveltekit build; if this is still happening please create a new issue
