### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by Jomy10** [janzheng/svelte-masonry#5]
This package has quite a lot of severe vulnerabilities. I copied the project and removed these dependencies: 
- rollup-plugin-node-builtins
- coeur
- node-sass

It seems to still be working fine and I also couldn't find these used anywhere. Consider removing these?

**Comment by roobscoob** [comment]
is this fork public?

**Comment by Jomy10** [comment]
My bad. I've made a pull request.

**Comment by janzheng** [comment]
Closing as I moved this to a new Sveltekit repo, with better demos.
