### ISSUE TITLE
Unable to install on Apple Silicon because of noda-sass dependency

### ISSUE THREAD

**Issue by nileshtrivedi** [janzheng/svelte-masonry#7]
node-sass currently does not work on Apple ARM machines like those with M1 chips. [Related Issue](https://github.com/sass/node-sass/issues/3033)

Additionally, node-sass involves many other complex dependencies like node-gyp which requires Python to be installed. All that for a masonry layout seems an overkill. Could svelte-masonry work without depending on node-sass?

**Comment by janzheng** [comment]
Thanks for that; I completely moved everything to Sveltekit. This issue should be fixed (I'm running on M3 now)
